disable-require = false
#swarm-resource = "DOCKER_RESOURCE_GPU"

[nvidia-container-cli]
#root = "/run/nvidia/driver"
path = "/snap/microk8s/current/usr/bin/nvidia-container-cli"
environment = []
debug = "/var/snap/microk8s/current/var/log/nvidia-container-toolkit.log"
#ldcache = "/etc/ld.so.cache"
load-kmods = true
#no-cgroups = false
#user = "root:video"
ldconfig = "@/sbin/ldconfig.real"
#alpha-merge-visible-devices-envvars = false

[nvidia-container-runtime]
debug = "/var/snap/microk8s/current/var/log/nvidia-container-runtime.log"
